"use strict";
// Generated by https://quicktype.io
Object.defineProperty(exports, "__esModule", { value: true });
exports.Legality = void 0;
var Legality;
(function (Legality) {
    Legality["Legal"] = "legal";
    Legality["NotLegal"] = "not_legal";
})(Legality = exports.Legality || (exports.Legality = {}));
//# sourceMappingURL=Cards.js.map